---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Creating a file with content
      copy:
        dest: "/home/ubuntu/success"
        content: |
          This is ansible
          generated file

    - name: Add group assignment in control
      group:
        name: assignment
        gid: 1234
        state: present

    - name: Add user devops to Assignment group
      user:
        name: devops
        shell: /bin/bash
        password: devops
        groups: sudo, assignment
        append: yes

    - name: Create .ssh directory if non-existent
      file:
        path: /home/devops/.ssh
        state: directory
        owner: devops
        group: devops
        mode: 0700

    - name: Generate an OpenSSH keypair 2048 bits
      openssh_keypair:
        path: "/home/devops/.ssh/id_rsa"
        size: 2048
        force: True
        owner: devops
        group: devops
